Tweaked maketarball so it doesn't mess everything up if the checkout fails.
git-svn-id: https://svn.participatoryculture.org/svn/dtv/trunk@7850 bce20531-a64c-4166-8316-56baf4a01729

Original sha1: a9fa680c5dcb13c70a529d10f2c75a8f6c6b4995

diff --git a/resources/tv/maketarball b/resources/tv/maketarball
--- a/resources/tv/maketarball
+++ b/resources/tv/maketarball
@@ -37,6 +37,14 @@ else
     fi
 fi
 
+if [ -e tv ]
+then
+    echo "Checkout successful."
+else
+    echo "Checkout failed!  See above for details."
+    exit $?;
+fi
+
 cd tv
 
 # go through app.config.template and expand the revision-related properties
